name: remote_file_explorer
description: "A new Flutter project."
publish_to: 'none'
version: 1.29.0+48

environment:
  sdk: ^3.7.0

dependencies:
  crypto: ^3.0.7
  cryptography: ^2.7.0
  dio: ^5.9.2
  dynamic_color: ^1.7.0
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^10.3.1
  mobile_scanner: ^7.2.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  photo_view: ^0.15.0
  pdfx: ^2.9.2
  flutter_markdown: ^0.7.6
  just_audio: ^0.9.43
  video_player: ^2.9.5
  chewie: ^1.11.3
  package_info_plus: ^9.0.1
  share_plus: ^10.1.4
  receive_sharing_intent: ^1.8.1
  photo_manager: ^3.6.1
  connectivity_plus: ^6.1.0
  nsd: ^5.0.1
  battery_plus: ^6.2.0
  local_auth: ^2.3.0
  flutter_local_notifications: ^18.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  just_audio_platform_interface: ^4.6.0
  plugin_platform_interface: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
