name: remote_file_explorer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  crypto: ^3.0.7
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
