//! Replays answers frozen from the Go search index and the Go recents walk (tests/data/index_golden.json). The file
//! was generated by the Go implementation at commit c792748a (`TestGenerateIndexGoldens`, see git history) and
//! carries the fixture tree it came from, so these tests keep guarding that behaviour now that the Go index is gone.
//! The Go adapter replays the same file in agent/internal/server (TestSidecarIndexMatchesFrozenGoIndex).
#![cfg(unix)]

use rfe_indexd::filter::{Compiled, Filters};
use rfe_indexd::index::{Index, Limits};
use rfe_indexd::recents;
use serde::Deserialize;
use std::fs;
use std::os::unix::fs::symlink;
use std::path::{Path, PathBuf};
use std::sync::atomic::AtomicBool;

#[derive(Deserialize)]
struct Golden {
    fixture: Vec<Fx>,
    queries: Vec<Query>,
    recents: Vec<Recents>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Fx {
    rel: String,
    kind: String,
    #[serde(default)]
    size: u64,
    #[serde(default)]
    target: String,
    mtime_ns: i64,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Want {
    path: String,
    is_dir: bool,
    size: u64,
    mtime_ns: i64,
    is_symlink: bool,
    #[serde(default)]
    target: String,
}

#[derive(Deserialize)]
struct Query {
    raw: String,
    filters: Filters,
    roots: Vec<String>,
    limit: usize,
    truncated: bool,
    entries: Vec<Want>,
}

#[derive(Deserialize)]
struct Recents {
    root: String,
    limit: usize,
    entries: Vec<Want>,
}

struct World {
    _tmp: tempfile::TempDir,
    root: String,
    outside: String,
}

impl World {
    fn sub(&self, s: &str) -> String {
        s.replace("$ROOT", &self.root)
            .replace("$OUTSIDE", &self.outside)
    }
}

fn set_times(p: &Path, mtime_ns: i64) {
    use rustix::fs::{utimensat, AtFlags, Timespec, Timestamps, CWD};
    let ts = Timespec {
        tv_sec: mtime_ns.div_euclid(1_000_000_000),
        tv_nsec: mtime_ns.rem_euclid(1_000_000_000),
    };
    utimensat(
        CWD,
        p,
        &Timestamps {
            last_access: ts,
            last_modification: ts,
        },
        AtFlags::SYMLINK_NOFOLLOW,
    )
    .unwrap();
}

fn materialize(g: &Golden) -> World {
    let tmp = tempfile::tempdir().unwrap();
    let root: PathBuf = tmp.path().join("root");
    let outside: PathBuf = tmp.path().join("outside");
    fs::create_dir_all(&root).unwrap();
    fs::create_dir_all(&outside).unwrap();
    fs::write(outside.join("secret.txt"), b"x").unwrap();
    let w = World {
        root: root.to_str().unwrap().to_string(),
        outside: outside.to_str().unwrap().to_string(),
        _tmp: tmp,
    };
    for f in g.fixture.iter().filter(|f| f.kind == "dir") {
        fs::create_dir_all(root.join(&f.rel)).unwrap();
    }
    for f in g.fixture.iter().filter(|f| f.kind == "file") {
        fs::write(root.join(&f.rel), vec![0u8; f.size as usize]).unwrap();
    }
    for f in g.fixture.iter().filter(|f| f.kind == "link") {
        symlink(w.sub(&f.target), root.join(&f.rel)).unwrap();
    }
    // Files and links first, then directories deepest-first (the fixture lists parents before children), so that
    // creating an entry never disturbs an mtime that was already set.
    for f in g.fixture.iter().filter(|f| f.kind != "dir") {
        set_times(&root.join(&f.rel), f.mtime_ns);
    }
    for f in g.fixture.iter().rev().filter(|f| f.kind == "dir") {
        set_times(&root.join(&f.rel), f.mtime_ns);
    }
    w
}

fn load() -> Golden {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/index_golden.json");
    serde_json::from_slice(&fs::read(path).unwrap()).unwrap()
}

fn check(ctx: &str, w: &World, got: &[rfe_indexd::entry::WireEntry], want: &[Want]) {
    let render = |it: Vec<(String, bool, u64, i64, bool, String)>| format!("{it:#?}");
    let g: Vec<_> = got
        .iter()
        .map(|e| {
            let size = if e.is_dir || e.is_symlink { 0 } else { e.size };
            (
                e.path.clone(),
                e.is_dir,
                size,
                e.mtime_ns,
                e.is_symlink,
                e.symlink_target.clone(),
            )
        })
        .collect();
    let x: Vec<_> = want
        .iter()
        .map(|e| {
            (
                w.sub(&e.path),
                e.is_dir,
                e.size,
                e.mtime_ns,
                e.is_symlink,
                w.sub(&e.target),
            )
        })
        .collect();
    assert!(
        g == x,
        "{ctx}\n--- Go (frozen)\n{}\n--- Rust\n{}",
        render(x),
        render(g)
    );
}

#[test]
fn index_answers_match_the_frozen_go_index() {
    let g = load();
    assert!(g.queries.len() > 200, "golden looks truncated");
    let w = materialize(&g);
    let idx = Index::build(
        std::slice::from_ref(&w.root),
        Limits {
            max_entries: 1_000_000,
            max_bytes: 1 << 30,
        },
        &AtomicBool::new(false),
    );
    for q in &g.queries {
        let roots: Vec<String> = q.roots.iter().map(|r| w.sub(r)).collect();
        let (got, truncated) =
            idx.query(&Compiled::new(clone_filters(&q.filters)), &roots, q.limit);
        let ctx = format!("{} roots={:?} limit={}", q.raw, q.roots, q.limit);
        assert_eq!(truncated, q.truncated, "truncated flag: {ctx}");
        check(&ctx, &w, &got, &q.entries);
    }
}

#[test]
fn recents_match_the_frozen_go_walk() {
    let g = load();
    let w = materialize(&g);
    for r in &g.recents {
        let root = w.sub(&r.root);
        let (got, partial) = recents::scan(&[root], r.limit, None, &AtomicBool::new(false));
        assert!(!partial);
        check(
            &format!("root {} limit {}", r.root, r.limit),
            &w,
            &got,
            &r.entries,
        );
    }
}

// `Filters` is only Deserialize; round-trip through its JSON shape to reuse one value several times.
fn clone_filters(f: &Filters) -> Filters {
    Filters {
        glob: f.glob.clone(),
        needle: f.needle.clone(),
        types: f.types.clone(),
        exts: f.exts.clone(),
        min_size: f.min_size,
        max_size: f.max_size,
        mod_after_ns: f.mod_after_ns,
        mod_before_ns: f.mod_before_ns,
    }
}
