import data from './licenses.json';

export type LicensePackage = { n: string; v: string; l: string; t: string | null };

/** Third-party JavaScript packages in the app bundle (generated by scripts/gen-licenses.mjs) with their license texts. */
export const bundledPackages = data.packages as LicensePackage[];
export const licenseText = (hash: string | null): string | null => (hash === null ? null : ((data.texts as Record<string, string>)[hash] ?? null));

/** Native code the app builds in that is not an npm package. Each is under the license shown. */
export const nativeComponents: { name: string; license: string }[] = [
  { name: 'React Native and Hermes', license: 'MIT' },
  { name: 'OkHttp and Okio (pinned HTTPS transport)', license: 'Apache-2.0' },
  { name: 'AndroidX libraries', license: 'Apache-2.0' },
  { name: 'flutter_secure_storage Android code (secure storage kept from the Flutter app)', license: 'BSD-3-Clause' },
  { name: 'Kotlin standard library and coroutines', license: 'Apache-2.0' },
];
