import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:path_provider/path_provider.dart';

import '../../core/l10n_ext.dart';
import '../../core/models/host.dart';
import '../../core/storage/host_store.dart';
import '../../core/ui/feedback.dart';
import '../transfers/transfer_state.dart';

/// Decoded payload from a device-to-device hand-off QR (see
/// `qr_generate_screen.dart`): `{"certFingerprint":"...","path":"...","name":"..."}`.
class HandoffPayload {
  const HandoffPayload({
    required this.certFingerprint,
    required this.path,
    required this.name,
  });

  final String certFingerprint;
  final String path;
  final String name;

  /// Parses [raw] (the scanned barcode text) into a [HandoffPayload], or
  /// returns null if it isn't valid JSON or is missing a required field.
  static HandoffPayload? tryParse(String raw) {
    try {
      final json = jsonDecode(raw) as Map<String, dynamic>;
      final fp = json['certFingerprint'] as String?;
      final path = json['path'] as String?;
      final name = json['name'] as String?;
      if (fp == null || path == null || name == null) return null;
      return HandoffPayload(certFingerprint: fp, path: path, name: name);
    } catch (_) {
      return null;
    }
  }
}

/// Finds the receiver's own paired [Host] whose `certFingerprint` matches
/// [certFingerprint] — i.e. the same agent the sender is paired to — or
/// returns null if this device isn't paired to that PC.
///
/// Pure and unit-testable on its own (see `test/features/handoff/`):
/// `Host.id` is per-device and NOT comparable across phones (it's the
/// device's own row in the agent's `devices` table), so matching must go
/// through `certFingerprint`, which is identical for every device paired to
/// the same agent.
Host? matchHandoffHost(List<Host> hosts, String certFingerprint) {
  for (final host in hosts) {
    if (host.certFingerprint == certFingerprint) return host;
  }
  return null;
}

/// Scans a hand-off QR generated by `QrGenerateSheet` on another phone
/// paired to the same agent, resolves it to one of this device's own paired
/// hosts, and enqueues a normal download (this device's own token, the
/// existing resumable transfer queue, saved to Downloads exactly like any
/// other download).
class QrScanScreen extends ConsumerStatefulWidget {
  const QrScanScreen({super.key});

  @override
  ConsumerState<QrScanScreen> createState() => _QrScanScreenState();
}

class _QrScanScreenState extends ConsumerState<QrScanScreen> {
  bool _processing = false;

  Future<void> _onBarcodeDetected(BarcodeCapture capture) async {
    if (_processing) return;
    final raw = capture.barcodes.firstOrNull?.rawValue;
    if (raw == null) return;

    final payload = HandoffPayload.tryParse(raw);
    if (payload == null) {
      showError(context, context.l10n.invalidQrFormat);
      return;
    }

    setState(() => _processing = true);
    try {
      final store = await ref.read(hostStoreProvider.future);
      final host = matchHandoffHost(store.listHosts(), payload.certFingerprint);
      if (host == null) {
        if (mounted) showError(context, context.l10n.qrHandoffNoHostMatch);
        return;
      }

      final dir =
          await getDownloadsDirectory() ??
          await getApplicationDocumentsDirectory();
      final localPath = '${dir.path}/${payload.name}';
      ref
          .read(transferQueueProvider.notifier)
          .enqueue(
            TransferTask.download(
              remotePath: payload.path,
              localPath: localPath,
              host: host,
            ),
          );

      if (mounted) {
        showSuccess(context, context.l10n.downloadingFile(payload.name));
        Navigator.of(context).pop();
      }
    } finally {
      if (mounted) setState(() => _processing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(context.l10n.receiveFileTitle)),
      body: Stack(
        children: [
          MobileScanner(onDetect: _onBarcodeDetected),
          if (_processing) const Center(child: CircularProgressIndicator()),
        ],
      ),
    );
  }
}
