import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:path_provider/path_provider.dart';

import '../../core/l10n_ext.dart';
import '../../core/models/host.dart';
import '../../core/storage/host_store.dart';
import '../../core/theme/tokens.dart';
import '../../core/ui/feedback.dart';
import '../transfers/transfer_state.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

/// Decoded payload from a device-to-device hand-off QR (see
/// `qr_generate_screen.dart`): `{"certFingerprint":"...","path":"...","name":"..."}`.
class HandoffPayload {
  const HandoffPayload({
    required this.certFingerprint,
    required this.path,
    required this.name,
  });

  final String certFingerprint;
  final String path;
  final String name;

  /// Parses [raw] (the scanned barcode text) into a [HandoffPayload], or
  /// returns null if it isn't valid JSON or is missing a required field.
  static HandoffPayload? tryParse(String raw) {
    try {
      final json = jsonDecode(raw) as Map<String, dynamic>;
      final fp = json['certFingerprint'] as String?;
      final path = json['path'] as String?;
      final name = json['name'] as String?;
      if (fp == null || path == null || name == null) return null;
      if (!isSafeLocalName(name)) return null;
      return HandoffPayload(certFingerprint: fp, path: path, name: name);
    } catch (_) {
      return null;
    }
  }
}

/// True if [name] is safe to use as a single local filename component: no
/// separators (rules out `../` traversal and absolute/UNC/volume prefixes),
/// no control characters, not `.`/`..`/empty, bounded length. `p.basename`
/// alone isn't a cross-platform validator — a bare `\` or `:` still passes
/// it while meaning something different to a Windows filesystem than to the
/// Dart string that formed the local path (PR-14).
bool isSafeLocalName(String name) {
  if (name.isEmpty || name.length > 255) return false;
  if (name == '.' || name == '..') return false;
  if (RegExp(r'[\x00-\x1f\\/:*?"<>|]').hasMatch(name)) return false;
  return true;
}

/// Finds the receiver's own paired [Host] whose `certFingerprint` matches
/// [certFingerprint] — i.e. the same agent the sender is paired to — or
/// returns null if this device isn't paired to that PC.
///
/// Pure and unit-testable on its own (see `test/features/handoff/`):
/// `Host.id` is per-device and NOT comparable across phones (it's the
/// device's own row in the agent's `devices` table), so matching must go
/// through `certFingerprint`, which is identical for every device paired to
/// the same agent.
Host? matchHandoffHost(List<Host> hosts, String certFingerprint) {
  for (final host in hosts) {
    if (host.certFingerprint == certFingerprint) return host;
  }
  return null;
}

/// Scans a hand-off QR generated by `QrGenerateSheet` on another phone
/// paired to the same agent, resolves it to one of this device's own paired
/// hosts, and enqueues a normal download (this device's own token, the
/// existing resumable transfer queue, saved to Downloads exactly like any
/// other download).
class QrScanScreen extends ConsumerStatefulWidget {
  const QrScanScreen({super.key});

  @override
  ConsumerState<QrScanScreen> createState() => _QrScanScreenState();
}

class _QrScanScreenState extends ConsumerState<QrScanScreen> {
  bool _processing = false;
  final _controller = MobileScannerController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _onBarcodeDetected(BarcodeCapture capture) async {
    if (_processing) return;
    final raw = capture.barcodes.firstOrNull?.rawValue;
    if (raw == null) return;

    final payload = HandoffPayload.tryParse(raw);
    if (payload == null) {
      showError(context, context.l10n.invalidQrFormat);
      return;
    }

    setState(() => _processing = true);
    try {
      final store = await ref.read(hostStoreProvider.future);
      final host = matchHandoffHost(store.listHosts(), payload.certFingerprint);
      if (host == null) {
        if (mounted) showError(context, context.l10n.qrHandoffNoHostMatch);
        return;
      }

      final dir =
          await getDownloadsDirectory() ??
          await getApplicationDocumentsDirectory();
      final localPath = '${dir.path}/${payload.name}';
      ref
          .read(transferQueueProvider.notifier)
          .enqueue(
            TransferTask.download(
              remotePath: payload.path,
              localPath: localPath,
              host: host,
            ),
          );

      if (mounted) {
        showSuccess(context, context.l10n.downloadingFile(payload.name));
        Navigator.of(context).pop();
      }
    } finally {
      if (mounted) setState(() => _processing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    // Full-bleed dark scanner with a corner-bracket viewfinder, matching the
    // mockup's `scr-qr-scan` chrome (see qr_generate_screen.dart's sibling
    // sheet for the sending side of this same hand-off feature).
    return Scaffold(
      backgroundColor: Colors.black,
      body: Stack(
        children: [
          MobileScanner(controller: _controller, onDetect: _onBarcodeDetected),
          SafeArea(
            child: Column(
              children: [
                Padding(
                  padding: const EdgeInsets.symmetric(
                    horizontal: Spacing.md,
                    vertical: Spacing.sm,
                  ),
                  child: Row(
                    children: [
                      _DarkIconButton(
                        icon: LucideIcons.arrowLeft,
                        onTap: () => Navigator.of(context).pop(),
                      ),
                      const Spacer(),
                      Text(
                        context.l10n.receiveFileTitle,
                        style: const TextStyle(
                          color: Colors.white,
                          fontSize: 19,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      const Spacer(),
                      _DarkIconButton(
                        icon: LucideIcons.flashlight,
                        onTap: () => _controller.toggleTorch(),
                      ),
                    ],
                  ),
                ),
                const Spacer(),
                const Center(
                  child: SizedBox(
                    width: 230,
                    height: 230,
                    child: _CornerBracketBox(
                      cornerSize: 36,
                      borderWidth: 4,
                      inset: 0,
                      scanlineHeight: 230,
                    ),
                  ),
                ),
                const Spacer(),
                Padding(
                  padding: const EdgeInsets.fromLTRB(
                    Spacing.lg,
                    0,
                    Spacing.lg,
                    Spacing.xl,
                  ),
                  child: Text(
                    context.l10n.qrHandoffScanHint,
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white.withValues(alpha: 0.7),
                      fontSize: 12.5,
                    ),
                  ),
                ),
              ],
            ),
          ),
          if (_processing)
            const ColoredBox(
              color: Color(0x66000000),
              child: Center(child: CircularProgressIndicator()),
            ),
        ],
      ),
    );
  }
}

/// Translucent circular icon button on a dark camera background — the
/// mockup's `.iconbtn` treatment for full-screen scanner appbars.
class _DarkIconButton extends StatelessWidget {
  const _DarkIconButton({required this.icon, required this.onTap});

  final IconData icon;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.white.withValues(alpha: 0.08),
      shape: const CircleBorder(),
      child: InkWell(
        customBorder: const CircleBorder(),
        onTap: onTap,
        child: SizedBox(
          width: 34,
          height: 34,
          child: Icon(icon, color: Colors.white, size: 19),
        ),
      ),
    );
  }
}

/// Four L-shaped corner brackets around a square viewfinder, with an
/// animated glowing scanline — the mockup's live-scan viewfinder chrome
/// (see pairing_screen.dart for the static placeholder variant).
class _CornerBracketBox extends StatefulWidget {
  const _CornerBracketBox({
    required this.cornerSize,
    required this.borderWidth,
    required this.inset,
    required this.scanlineHeight,
  });

  final double cornerSize;
  final double borderWidth;
  final double inset;

  /// Animates a glowing horizontal line up/down across this height,
  /// matching the mockup's `@keyframes scanline`.
  final double scanlineHeight;

  @override
  State<_CornerBracketBox> createState() => _CornerBracketBoxState();
}

class _CornerBracketBoxState extends State<_CornerBracketBox>
    with SingleTickerProviderStateMixin {
  late final AnimationController _ctrl;

  @override
  void initState() {
    super.initState();
    _ctrl = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 2200),
    )..repeat(reverse: true);
  }

  @override
  void dispose() {
    _ctrl.dispose();
    super.dispose();
  }

  Widget _bracket(Alignment alignment) {
    final isTop = alignment.y < 0;
    final isLeft = alignment.x < 0;
    final side = BorderSide(color: Brand.seed, width: widget.borderWidth);
    return Positioned(
      top: isTop ? widget.inset : null,
      bottom: !isTop ? widget.inset : null,
      left: isLeft ? widget.inset : null,
      right: !isLeft ? widget.inset : null,
      child: SizedBox(
        width: widget.cornerSize,
        height: widget.cornerSize,
        child: DecoratedBox(
          decoration: BoxDecoration(
            border: Border(
              top: isTop ? side : BorderSide.none,
              bottom: !isTop ? side : BorderSide.none,
              left: isLeft ? side : BorderSide.none,
              right: !isLeft ? side : BorderSide.none,
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final scanlineHeight = widget.scanlineHeight;
    return Stack(
      children: [
        for (final a in const [
          Alignment.topLeft,
          Alignment.topRight,
          Alignment.bottomLeft,
          Alignment.bottomRight,
        ])
          _bracket(a),
        AnimatedBuilder(
          animation: _ctrl,
          builder: (context, _) {
            final travel = scanlineHeight / 2 - 8;
            final y = travel * (2 * _ctrl.value - 1);
            return Positioned(
              left: 8,
              right: 8,
              top: scanlineHeight / 2 + y,
              child: Container(
                height: 2,
                decoration: BoxDecoration(
                  color: Brand.seed,
                  boxShadow: [
                    BoxShadow(
                      color: Brand.seed.withValues(alpha: 0.6),
                      blurRadius: 8,
                    ),
                  ],
                ),
              ),
            );
          },
        ),
      ],
    );
  }
}
